name: Lint

on:
  - pull_request

jobs:
  linter_name:
    name: Black-Flake8-Mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Black Lint
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"

      - name: Set up Python environment for Flake8
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Flake8 Lint
        uses: py-actions/flake8@v2

      - name: Set up Python environment for MyPy
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install Dependencies
        run: |
          pip install mypy
      - name: mypy
        run: |
          mypy src/