name: Unit Test

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Test with unittest
        run: |
          python -m unittest discover -s ./test  -p 'test_*.py'
